name: CI Testing Windows
on: [push, pull_request]

env:
  CPM_SOURCE_CACHE: cpm-cache
  FPIMPL_BUILD_DIR: build

jobs:
  tests-windows:
    runs-on: windows-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: actions/cache@v3
        with:
          key: cpm-cache-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          path: ${{ env.CPM_SOURCE_CACHE }}
          enableCrossOsArchive: true
      - 
        name: Configure project
        run: | 
          cmake -B ${{ env.FPIMPL_BUILD_DIR }} -DFPIMPL_BUILD_EXAMPLE=OFF -DFPIMPL_ENABLE_WALL_WERROR=ON
      - 
        name: Build project
        run: cmake --build ${{ env.FPIMPL_BUILD_DIR }} --parallel --config Release
      - 
        name: Run tests
        run: ctest --parallel 12 --test-dir ${{ env.FPIMPL_BUILD_DIR }} --no-tests=error --output-on-failure
