name: CI
on: [push, pull_request]

env:
  CPM_SOURCE_CACHE: ${{ vars.CPM_SOURCE_CACHE }}

jobs:
  cmake-configure-check:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        cmake_version: ['3.21.x', 'latest']
    steps:
      -
        uses: actions/checkout@v4
      - 
        name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: ${{ matrix.cmake_version }}
      -
        uses: actions/cache@v3
        with:
          key: cpm-cache-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          path: ${{ vars.CPM_SOURCE_CACHE }}
          enableCrossOsArchive: true
      - 
        name: Configure project
        run: cmake -B ~/fpimpl-build
