name: CI
on: [push, pull_request]
jobs:
  cmake-configure-check:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      - 
        name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.21.x'
      - 
        name: Configure project
        run: cmake -B build
  
